name:                solidity-service
version:             0.1.0.0
github:              "krisajenkins/solidity-service"
license:             AllRightsReserved
copyright:           "2018 IOHK"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/krisajenkins/solidity-service#readme>

dependencies:
- aeson
- attoparsec
- base
- bytestring
- containers
- unordered-containers
- directory
- system-filepath
- filepath
- http-media
- lens
- process
- lens-aeson
- mtl
- temporary
- servant
- servant-server
- text
- time
- transformers
- vector
- wai
- wai-extra
- data-default-class
- warp
- optparse-applicative
- gitrev
- monad-logger

ghc-options:
- -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wmissing-import-lists

library:
  source-dirs: src

executables:
  solidity-service:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solidity-service

tests:
  solidity-service-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - hspec
    - hspec-core
    - solidity-service
